version: "2"
services:
  memcached:
    image: memcached:latest
    container_name: memcached
    command: ["-m", "4096"] # 指定最大内存(单位M)
    # restart: always
    ports:
      - 11211:11211
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - $PWD/../../workspace/:/workspace/
