version: "2"
services:
  centos7:
    image: centos7_java:v1.0
    container_name: centos7_java
    ports:
      - 6008:6008
      - 8000:8000
      - 27000:27000
      - 27001:27001
      - 27034:27034
      - 29200:29200
      - 29201:29201
      - 25100:25100
    privileged: true
    # networks:
    #   - default
    # entrypoint: [ "/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - $PWD/../../workspace/:/workspace/

# networks:
#   default:
#     driver: bridge



# docker run -itd --privileged --name centos-dev -v /Users/gaea/docker/:/data/ -p 81:80 centos-dev:latest /bin/bash
