version: '3'
services:

  mysql:
    image: mysql:5.7 #镜像名称以及版本
    # restart: always #重启docker后该容器也重启
    container_name: mysql5.7 #容器名称
    command: #构建容器后所执行的命令
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower-case-table-names=1 #忽略数据表名大小写 
    environment:
      MYSQL_ROOT_PASSWORD: root #指定用户密码,有时无法生效的原因是volumes要清理掉重新挂载具体见readme
      TZ: Asia/Shanghai
    ports:
      - 3306:3306 #本地端口号与容器内部端口号
    volumes: #指定挂载目录
      - $PWD/var/lib/mysql:/var/lib/mysql
      - $PWD/etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      - $PWD/var/log:/var/log
      - $PWD/backup:/data/backup
