version: "2"
services:
  centos7_redis:
    image: centos7_redis:v1.0
    container_name: centos7_redis
    restart: always
    ports:
      - 6379:6379
    stdin_open: true
    tty: true
    volumes:
      - $PWD/../../workspace/:/workspace/
